name: Grype Scan

on:
  pull_request:
    branches:
      - main
  schedule:
    # Run daily at 2 AM to catch new CVEs
    - cron: "0 2 * * *"

jobs:
  grype-scan:
    runs-on: ubuntu-latest
    # Permissions key is required for CodeQL SARIF Upload, per the docs:
    # https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Build the Container image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest
      - uses: anchore/scan-action@v6
        id: scan
        with:
          image: "localbuild/testimage:latest"
          severity-cutoff: medium
          output-format: table
      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: grype-scan-report
          path: ${{ steps.scan.outputs.table }}
